### ISSUE TITLE
server.js#L50 seems overload logic

### ISSUE THREAD

**Issue by Doaxan** [Hellwest/NodeJS-chat#1]
Don't you think that https://github.com/Hellwest/NodeJS-chat/blob/master/server.js#L50 seems overload logic with 'if', maybe you can rewrite it simply?

**Comment by Doaxan** [comment]
Or, maybe, move some logic to functions? At your discretion

**Comment by Hellwest** [comment]
> overload logic with 'if'

I'm working on it, now there's one less IF
